x-scratch:
  DOCKER_HOST=https://nginx-proxy:2376
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 2376
    networks:
      - docker-socket-network
    depends_on:
      - docker-socket-proxy
  docker-socket-proxy:
    image: dsock-proxy:latest
    container_name: docker-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-socket-network
    environment:
      - CONTAINERS=1
networks:
  docker-socket-network:
    external: true